import { chromium } from "playwright-core";
const SP = process.argv[2];
const URL = process.argv[3] ?? "http://localhost:3100/?debug&world&lite&npcs=theo";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args: ["--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--autoplay-policy=no-user-gesture-required"] });
const page = await browser.newPage({ viewport: { width: 960, height: 540 } });
const logs = [];
page.on("console", (m) => { if (m.type() === "error") logs.push(`[error] ${m.text().slice(0, 300)}`); });
page.on("pageerror", (e) => logs.push(`[pageerror] ${e.message} ${(e.stack || "").slice(0, 400)}`));
await page.addInitScript(() => localStorage.setItem("bh-profile", JSON.stringify({ state: { firstName: "Alex", lastName: "Martin", avatar: 2, arrivalSeen: true, flags: { hubIntro: "1", worldIntro: "1" } }, version: 4 })));
await page.goto(URL);
const G = (fn, arg) => page.evaluate(fn, arg);
const until = async (fn, t = 120000, arg) => { const t0 = Date.now(); while (Date.now() - t0 < t) { if (await G(fn, arg)) return true; await page.waitForTimeout(200); } return false; };
let i = 0;
const snap = async (n) => page.screenshot({ path: `${SP}/p${String(i++).padStart(2, "0")}-${n}.png` });
const results = [];
const ok = (name, pass, info = "") => { results.push(`${pass ? "OK  " : "FAIL"} ${name} ${info}`); console.log(results.at(-1)); };
const st = () => G(() => { const w = window.__game.useWorld.getState(); const p = window.__game.worldRuntime.player; return { active: w.active, prompt: w.prompt?.id ?? null, menu: w.menu?.title ?? null, toast: w.toast?.text ?? null, hub: window.__game.useHub.getState().active, view: window.__game.useHub.getState().view, x: +p.x.toFixed(2), z: +p.z.toFixed(2), frozen: window.__game.worldRuntime.frozen }; });
const proj = (x, z) => G(([x, z]) => { const { camera, size } = window.__r3f; const v = camera.position.clone().set(x, 0, z).project(camera); return [(v.x * 0.5 + 0.5) * size.width, (-v.y * 0.5 + 0.5) * size.height]; }, [x, z]);
const count = () => G(() => (window.__game.useProfile.getState().decor ?? []).length);
try {
  await until(() => !!window.__bh && !!window.__game, 180000);
  await G(() => { window.__bh.gsap.ticker.lagSmoothing(0); });
  if (!(await until(() => window.__worldReady, 180000))) throw new Error("world never ready");
  await until(() => window.__game.useWorld.getState().active && !window.__game.worldRuntime.frozen, 60000);
  await page.waitForTimeout(1500);
  await page.keyboard.press("b");
  ok("B ouvre la décoration", await until(() => window.__game.useWorld.getState().edit, 5000));
  await page.waitForTimeout(2500);
  await page.getByRole("button", { name: "Déco", exact: true }).click();
  await page.getByRole("button", { name: /Figuier lyre/ }).click();
  const before = await count();
  const [sx, sy] = await proj(8.9, -8.4);
  console.log("screen", sx, sy);
  await page.mouse.move(sx - 20, sy - 10); await page.waitForTimeout(600);
  await page.mouse.move(sx, sy, { steps: 4 }); await page.waitForTimeout(1500);
  await snap("edit-ghost");
  await page.mouse.click(sx, sy);
  await page.waitForTimeout(1200);
  const after = await count();
  ok("pose d'un figuier au clic", after > before && after > 0, `avant=${before} après=${after} toast=${await G(() => window.__game.useWorld.getState().toast?.text)}`);
  await snap("edit-placed");
  // Déplacer : la plante
  await page.getByRole("button", { name: "Vos meubles" }).click();
  const decor0 = await G(() => window.__game.useProfile.getState().decor ?? []);
  const idx = decor0.findIndex((d) => d.type === "plant-tall");
  await page.getByRole("button", { name: "Déplacer" }).nth(idx).click();
  const [mx, my] = await proj(5.4, -11.2);
  await page.mouse.move(mx, my, { steps: 5 }); await page.waitForTimeout(1200);
  await page.mouse.click(mx, my); await page.waitForTimeout(1000);
  const moved = await G(() => window.__game.useProfile.getState().decor.find((d) => d.type === "plant-tall"));
  ok("déplacement au clic", moved && Math.abs(moved.x - 5.4) < 0.3, JSON.stringify(moved));
  // Refus sur le bureau
  await page.getByRole("button", { name: "Déco", exact: true }).click();
  await page.getByRole("button", { name: /Plante en pot/ }).click();
  const [dx, dy] = await proj(6.5, -10.25);
  await page.mouse.move(dx, dy, { steps: 4 }); await page.waitForTimeout(1200);
  const c1 = await count();
  await page.mouse.click(dx, dy); await page.waitForTimeout(800);
  ok("refus sur le bureau", (await count()) === c1, await G(() => window.__game.useWorld.getState().toast?.text));
  await page.keyboard.press("Escape"); await page.keyboard.press("Escape");
  ok("sortie décoration", await until(() => !window.__game.useWorld.getState().edit && !window.__game.worldRuntime.frozen, 5000));
  await page.waitForTimeout(1500); await snap("edit-after");
  // Le joueur peut marcher (collisions reconstruites) et s'asseoir
  await G(() => { const p = window.__game.worldRuntime.player; p.x = 6.2; p.z = -8.9; p.rot = Math.PI; });
  ok("bureau encore utilisable", await until(() => window.__game.useWorld.getState().prompt?.id === "desk", 6000));
} catch (e) { console.log("ERR", e.message); await snap("error"); }
console.log("\n" + results.join("\n"));
console.log("\nLOGS:\n" + (logs.slice(0, 20).join("\n") || "none"));
await browser.close();
