/**
 * Tableau d'enquête de l'affaire Meridian (préparation de l'affaire 2) : dix pièces, quatre connexions
 * justes. Chaque connexion est une contradiction que l'on pourra opposer à Daniel Rourke à la barre ;
 * deux pièces sont des fausses pistes (vraies, mais sans rien à en tirer).
 */
import type { BoardDef } from "@/engine/board/types";

export const MERIDIAN_BOARD: BoardDef = {
  id: "meridian-board",
  title: "Meridian — préparation de l'audience",
  required: 2,
  pieces: [
    {
      id: "p-invoice",
      kind: "document",
      title: "Facture Halvorsen n° 4471",
      lines: ["Émise le 28 décembre", "Montant : 84,6 M$", "« Prestations de transport 3 ans »"],
      source: "Grand livre Meridian",
      at: { x: 0.13, y: 0.2 },
      rot: -0.05,
      fromAnomaly: "cutoff",
    },
    {
      id: "p-contract",
      kind: "document",
      title: "Contrat Halvorsen",
      lines: ["Signé à Oslo le 3 janvier", "Début des prestations :", "15 janvier"],
      source: "Pièce 12 — obtenue de Halvorsen AS",
      at: { x: 0.38, y: 0.2 },
      rot: 0.04,
    },
    {
      id: "p-interview",
      kind: "quote",
      title: "Rourke sur Bloomberg TV",
      lines: ["« Meridian n'a aucune", "transaction avec des", "parties liées. Aucune. »"],
      source: "Transcription, 14 février",
      at: { x: 0.63, y: 0.2 },
      rot: -0.03,
    },
    {
      id: "p-orca",
      kind: "document",
      title: "Orca Partners LLC",
      lines: ["Registre du Delaware", "Gérante : Linda Rourke", "Siège : Wilmington"],
      source: "Extrait du registre des sociétés",
      at: { x: 0.88, y: 0.2 },
      rot: 0.06,
      fromAnomaly: "related",
    },
    {
      id: "p-memo9",
      kind: "note",
      title: "Note interne — D. Rourke",
      lines: ["« Durée d'amortissement", "des tracteurs portée", "à 9 ans. »"],
      source: "Mémo du 2 décembre",
      at: { x: 0.13, y: 0.8 },
      rot: 0.05,
      fromAnomaly: "depreciation",
    },
    {
      id: "p-maintenance",
      kind: "document",
      title: "Rapport de maintenance",
      lines: ["Flotte réformée après", "5,2 ans en moyenne", "(kilométrage > 900 000)"],
      source: "Direction technique Meridian",
      at: { x: 0.38, y: 0.8 },
      rot: -0.04,
    },
    {
      id: "p-stocks",
      kind: "note",
      title: "Stocks de pièces",
      lines: ["+38 % sur l'exercice", "pour un chiffre d'affaires", "à +13,7 %"],
      source: "Vos notes d'audit",
      at: { x: 0.63, y: 0.8 },
      rot: 0.03,
      fromAnomaly: "inventory",
    },
    {
      id: "p-warehouse",
      kind: "photo",
      title: "Entrepôt de Newark",
      lines: ["Registre des entrées :", "aucune livraison", "du 1er au 31 décembre"],
      source: "Photo d'un enquêteur privé",
      at: { x: 0.88, y: 0.8 },
      rot: -0.06,
    },
    {
      id: "p-bond",
      kind: "document",
      title: "Emprunt obligataire",
      lines: ["Émis en mars, 5,25 %", "Échéance 2031", "Financement : 400 tracteurs"],
      source: "Prospectus",
      at: { x: 0.75, y: 0.5 },
      rot: 0.02,
    },
    {
      id: "p-auditor",
      kind: "document",
      title: "Lettre du commissaire aux comptes",
      lines: ["« Comptes certifiés", "sans réserve »", "(exercice précédent)"],
      source: "Rapport annuel N-1",
      at: { x: 0.25, y: 0.5 },
      rot: -0.03,
    },
  ],
  links: [
    {
      id: "l-cutoff",
      a: "p-invoice",
      b: "p-contract",
      title: "Revenu anticipé",
      insight: "La facture de 84,6 M$ est antérieure à la signature du contrat : ce chiffre d'affaires n'existait pas au 31 décembre.",
      courtEvidence: "p-contract",
      weight: 30,
      lesson: "cutoff",
    },
    {
      id: "l-related",
      a: "p-interview",
      b: "p-orca",
      title: "Partie liée cachée",
      insight: "Rourke jure qu'il n'y a aucune partie liée ; Orca Partners est dirigée par sa femme.",
      courtEvidence: "p-orca",
      weight: 30,
      lesson: "related-parties",
    },
    {
      id: "l-depreciation",
      a: "p-memo9",
      b: "p-maintenance",
      title: "Neuf ans sur le papier, cinq sur la route",
      insight: "La direction technique réforme les camions à 5 ans ; les amortir sur 9 ans gonfle le résultat.",
      courtEvidence: "p-maintenance",
      weight: 25,
      lesson: "change-estimate",
    },
    {
      id: "l-stocks",
      a: "p-stocks",
      b: "p-warehouse",
      title: "Des stocks qui n'existent pas",
      insight: "Les stocks bondissent en décembre alors qu'aucune pièce n'est entrée dans l'entrepôt.",
      courtEvidence: "p-warehouse",
      weight: 15,
      lesson: "inventory",
    },
  ],
};
